# Generated by Django 4.2.10 on 2024-03-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0012_otherdes'),
        ('admin_mod', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('receiver_location', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('ordered_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.post')),
                ('receiver_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.user')),
            ],
        ),
    ]
