# Generated by Django 4.2.10 on 2024-03-12 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0008_emailverification'),
        ('provider', '0013_feedbacktab'),
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('feedback', models.CharField(default='', max_length=500)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.post')),
            ],
        ),
    ]
