<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-13 12:26
=======
# Generated by Django 4.2.10 on 2024-03-12 19:08
>>>>>>> 8f099e68669fa141d32ec3de1a9a29adca9676f3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_alter_order_date_time_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
