# Generated by Django 5.0.3 on 2024-03-13 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_alter_order_date_time_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
