# Generated by Django 4.2.10 on 2024-02-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_mod', '0002_admin_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='statics/provider/postpics')),
                ('category', models.CharField(choices=[('toys', 'Toys'), ('food', 'Food'), ('clothes', 'Clothes'), ('others', 'Others'), ('groceries', 'Groceries')], max_length=10)),
                ('drop_pickup', models.CharField(choices=[('drop', 'Drop'), ('pickup', 'Pickup')], max_length=10)),
                ('description_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('will_expire', models.CharField(choices=[('drop', 'Drop'), ('pickup', 'Pickup')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_mod.user')),
            ],
        ),
    ]
