# Generated by Django 4.2.10 on 2024-02-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('delivered', 'Delivered')], default='live', max_length=10),
        ),
    ]
