# Generated by Django 4.2.10 on 2024-02-29 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_post_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='will_expire',
            field=models.CharField(choices=[('expirable', 'Expirable or Perishable'), ('non_expirable', 'Not Expirable or Non Perishable')], max_length=25),
        ),
    ]
