# Generated by Django 4.2.10 on 2024-02-29 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0006_post_created_at_alter_post_will_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='toysDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('status', models.CharField(choices=[('new', 'New'), ('mint', 'Mint'), ('old', 'Old')], default='live', max_length=10)),
            ],
        ),
    ]
