# Generated by Django 4.2.10 on 2024-02-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_toysdes'),
    ]

    operations = [
        migrations.AddField(
            model_name='toysdes',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
