# Generated by Django 4.2.10 on 2024-02-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0009_rename_status_toysdes_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toysdes',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('mint', 'Mint'), ('old', 'Old')], max_length=10),
        ),
    ]
