# Generated by Django 4.2.10 on 2024-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0010_alter_toysdes_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='clothDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=1000)),
                ('gender', models.CharField(choices=[('male', 'For Male'), ('female', 'For Female'), ('both', 'For Both')], max_length=25)),
                ('condition', models.CharField(choices=[('new', 'New'), ('mint', 'Mint'), ('old', 'Old')], max_length=10)),
                ('size', models.CharField(choices=[('new', 'New'), ('mint', 'Mint'), ('old', 'Old')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='foodDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=1000)),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='groceryDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=1000)),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField()),
            ],
        ),
    ]
