# Generated by Django 4.2.10 on 2024-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0011_clothdes_fooddes_grocerydes'),
    ]

    operations = [
        migrations.CreateModel(
            name='otherDes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
