# Generated by Django 4.2.10 on 2024-03-11 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0008_emailverification'),
        ('provider', '0012_otherdes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
                ('feedback', models.CharField(default='', max_length=500)),
                ('given_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='admin_mod.user')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.post')),
            ],
        ),
    ]
