# Generated by Django 4.2.10 on 2024-03-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0013_feedbacktab'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mode',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
    ]
