# Generated by Django 4.2.10 on 2024-03-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0014_post_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latlong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
