# Generated by Django 4.2.10 on 2024-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='zerowaste_score',
            field=models.IntegerField(default=0),
        ),
    ]
