# Generated by Django 4.2.10 on 2024-03-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0006_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_verified',
        ),
    ]
