# Generated by Django 4.2.10 on 2024-03-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_mod', '0009_rename_name_admin_username_admin_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
